import pandas as pd
import utils.const as const

def get_map(cache_results=True):
    full_teams = []
    df_m = pd.read_csv(const.M_TEAM_NAME_PATH)
    df_w = pd.read_csv(const.W_TEAM_NAME_PATH)
    teams = df_m["TeamName"].values
    ids = df_m["TeamID"].values
    teams = ["_".join(team.split(" ")).lower() for team in teams]
    m_full_teams = [f"{team}_m_{y}" for y in range(2009, 2026) for team in teams]
    m_full_ids = [f"{id}_{y}" for y in range(2009, 2026) for id in ids]
    teams = df_w["TeamName"].values
    ids = df_w["TeamID"].values
    teams = ["_".join(team.split(" ")).lower() for team in teams]
    w_full_teams = [f"{team}_w_{y}" for y in range(2009, 2026) for team in teams]
    w_full_ids = [f"{id}_{y}" for y in range(2009, 2026) for id in ids]
    full_teams = m_full_teams + w_full_teams
    full_teams = replace(full_teams, "-", "_")
    full_teams = replace(full_teams, ".", "")
    full_teams = replace(full_teams, "'", "")
    full_ids = m_full_ids + w_full_ids
    # full_teams = [full_teams.append([f"{team}_M_{y}" for y in range(2009, 2026)]) for team in teams].flatten()
    # print(full_teams[:10], full_ids[:10])
    # print(len(full_teams), len(full_ids))
    if cache_results:
        import json
        import os
        os.makedirs("cache", exist_ok=True)
        with open("cache/id_to_team.json", "w") as f:
            json.dump(dict(zip(full_ids, full_teams)), f)
        with open("cache/team_to_id.json", "w") as f:
            json.dump(dict(zip(full_teams, full_ids)), f)
    return dict(zip(full_ids, full_teams)), dict(zip(full_teams, full_ids))
def replace(li, k, v):
    return [l.replace(k, v) for l in li]

def odds_rules(teams):
    teams = replace(teams, "-", "_")
    teams = replace(teams, ".", "")
    teams = replace(teams, "'", "")
    teams = replace(teams, "(", "")
    teams = replace(teams, ")", "")
    
    teams = replace(teams, "_state", "_st")
    teams = replace(teams, "saint", "st")
    teams = replace(teams, "university", "univ")
    teams = replace(teams, "_christian", "_chr")
    teams = replace(teams, "cal_st_", "cs_")
    teams = replace(teams, "uunc_", "unc_")
    
    
    teams = replace(teams, "loyola_maryland", "loyola_md")
    teams = replace(teams, "loyola_marymount", "loy_marymount")
    teams = replace(teams, "sacramento_st", "cs_sacramento")
    teams = replace(teams, "nc_st", "nc_state")
    teams = replace(teams, "st_johns_ny", "st_johns")
    teams = replace(teams, "uconn", "connecticut")
    teams = replace(teams, "ole_miss", "mississippi")
    teams = replace(teams, "kent_st", "kent")
    teams = replace(teams, "miami_ohio", "miami_oh")
    teams = replace(teams, "ut_martin", "tn_martin")
    teams = replace(teams, "northern_illinois", "n_illinois")
    teams = replace(teams, "george_washington", "g_washington")
    teams = replace(teams, "eastern_michigan", "e_michigan")
    teams = replace(teams, "east_washington", "e_washington")
    teams = replace(teams, "florida_atlantic", "fl_atlantic")
    teams = replace(teams, "georgia_southern", "ga_southern")
    teams = replace(teams, "florida_international", "florida_intl")
    teams = replace(teams, "eastern_illinois", "e_illinois")
    teams = replace(teams, "illinois_chi", "il_chicago")
    teams = replace(teams, "uic", "il_chicago")
    teams = replace(teams, "wisc_green_bay", "wi_green_bay")
    teams = replace(teams, "eastern_kentucky", "e_kentucky")
    teams = replace(teams, "central_michigan", "c_michigan")
    teams = replace(teams, "western_carolina", "w_carolina")
    teams = replace(teams, "charleston", "col_charleston")
    teams = replace(teams, "louisiana_monroe", "ulm")
    teams = replace(teams, "ul_monroe", "ulm")
    teams = replace(teams, "southeast_missouri_st", "se_missouri_st")
    teams = replace(teams, "umkc", "missouri_kc")
    teams = replace(teams, "little_rock", "ark_little_rock")
    teams = replace(teams, "ualr", "ark_little_rock")
    teams = replace(teams, "north_dakota_st", "n_dakota_st")
    teams = replace(teams, "south_dakota_st", "s_dakota_st")
    teams = replace(teams, "arkansas_pine_bluff", "ark_pine_bluff")
    teams = replace(teams, "southern_illinois", "s_illinois")
    teams = replace(teams, "northern_colorado", "n_colorado")
    teams = replace(teams, "middle_tenn_st", "mtsu")
    teams = replace(teams, "western_kentucky", "wku")
    teams = replace(teams, "louisiana_lafayette", "lafayette")
    teams = replace(teams, "coastal_carolina", "coastal_car")
    teams = replace(teams, "brigham_young", "byu")
    teams = replace(teams, "wisc_milwaukee", "wi_milwaukee")
    teams = replace(teams, "western_michigan", "w_michigan")
    teams = replace(teams, "miss_valley_st", "ms_valley_st")
    teams = replace(teams, "north_carolina_a&t", "nc_a&t")
    teams = replace(teams, "n_carolina_a&t", "nc_a&t")
    teams = replace(teams, "liu_sharks", "liu_brooklyn")
    teams = replace(teams, "umass", "massachusetts")
    teams = replace(teams, "stephen_", "s")
    teams = replace(teams, "prairie_view_a&m", "prairie_view")
    teams = replace(teams, "albany_great_danes", "suny_albany")
    teams = replace(teams, "st_francis_brooklyn", "st_francis_ny")
    teams = replace(teams, "texas_southern", "tx_southern")
    teams = replace(teams, "utsa_roadrunners", "ut_san_antonio")
    teams = replace(teams, "n_carolina_central", "nc_central")
    teams = replace(teams, "iu_indy", "iupui")
    teams = replace(teams, "iu_indianapolis", "iupui")
    teams = replace(teams, "western_illinois", "w_illinois")
    teams = replace(teams, "east_tennessee_st", "etsu")
    teams = replace(teams, "col_charleston_southern", "charleston_so")
    teams = replace(teams, "northwestern_st", "northwestern_la")
    teams = replace(teams, "st_marys", "st_marys_ca")
    teams = replace(teams, "st_marys_ca_ca", "st_marys_ca")
    teams = replace(teams, "mount_st_marys_ca", "mt_st_marys")
    teams = replace(teams, "csu_bakersfield", "cs_bakersfield")
    teams = replace(teams, "utah_valley_st", "utah_valley")
    teams = replace(teams, "ipfw", "pfw")
    teams = replace(teams, "purdue_fort_wayne", "pfw")
    teams = replace(teams, "northern_kentucky", "n_kentucky")
    teams = replace(teams, "usc_upstate", "sc_upstate")
    teams = replace(teams, "monmouth", "monmouth_nj")
    teams = replace(teams, "nebraska_o", "ne_omaha")
    teams = replace(teams, "siu_edwardsville", "siue")
    teams = replace(teams, "maryland_eastern_shore", "md_e_shore")
    teams = replace(teams, "md_east_shore", "md_e_shore")
    teams = replace(teams, "fairleigh_dickinson", "f_dickinson")
    teams = replace(teams, "south_carolina_st", "s_carolina_st")
    teams = replace(teams, "florida_gulf_coast", "fgcu")
    teams = replace(teams, "california_baptist", "cal_baptist")
    teams = replace(teams, "grambling_st", "grambling")
    teams = replace(teams, "eastern_washington", "e_washington")
    teams = replace(teams, "ut_rio_grande_valley", "utrgv")
    teams = replace(teams, "north_carolina_central", "nc_central")
    teams = replace(teams, "massachusetts_lowell", "ma_lowell")
    teams = replace(teams, "central_arkansas", "cent_arkansas")
    teams = replace(teams, "texas_a&m_corpus_christi", "tam_c_christi")
    teams = replace(teams, "texas_a&m_cc", "tam_c_christi")
    teams = replace(teams, "miami_w", "miami_fl_w")
    teams = replace(teams, "miami_m", "miami_fl_m")
    teams = replace(teams, "st_thomas_minnesota", "st_thomas_mn")
    teams = replace(teams, "st_thomas_minn", "st_thomas_mn")
    teams = replace(teams, "san_josé_st", "san_jose_st")
    teams = replace(teams, "ualbany", "suny_albany")
    teams = replace(teams, "app_st", "appalachian_st")
    teams = replace(teams, "south_carolina_upstate", "sc_upstate")
    teams = replace(teams, "long_island_univ", "liu_brooklyn")
    teams = replace(teams, "central_connecticut_st", "central_conn")
    teams = replace(teams, "central_connecticut", "central_conn")
    teams = replace(teams, "detroit_mercy", "detroit")
    teams = replace(teams, "seattle_u", "seattle")
    teams = replace(teams, "utsa", "ut_san_antonio")
    teams = replace(teams, "winston_salem", "w_salem_st")
    teams = replace(teams, "mississippi_valley_st", "ms_valley_st")
    teams = replace(teams, "kennesaw_st", "kennesaw")
    teams = replace(teams, "pennsylvania", "penn")
    teams = replace(teams, "centenary_louisiana", "centenary")
    teams = replace(teams, "centenary_la", "centenary")
    teams = replace(teams, "middle_tennessee", "mtsu")
    teams = replace(teams, "kansas_city", "missouri_kc")
    teams = replace(teams, "queens_royals", "queens_nc")
    teams = replace(teams, "queens_univ", "queens_nc")
    teams = replace(teams, "southern_w", "southern_univ_w")
    teams = replace(teams, "tx_southern_univ", "tx_southern")
    teams = replace(teams, "ga_southern_univ", "ga_southern")
    teams = replace(teams, "st_josephs_w", "st_josephs_pa_w")
    teams = replace(teams, "tx_a&m_commerce", "east_texas_a&m")
    teams = replace(teams, "bryant_univ", "bryant")
    
    teams = replace(teams, "omaha", "ne_omaha")
    teams = replace(teams, "ne_ne_omaha", "ne_omaha")
    teams = replace(teams, "nc_greensboro", "unc_greensboro")
    teams = replace(teams, "uunc_greensboro", "unc_greensboro")
    teams = replace(teams, "nc_wilmington", "unc_wilmington")
    teams = replace(teams, "uunc_wilmington", "unc_wilmington")
    teams = replace(teams, "green_bay", "wi_green_bay")
    teams = replace(teams, "wi_wi_green_bay", "wi_green_bay")
    teams = replace(teams, "mcneese", "mcneese_st")
    teams = replace(teams, "mcneese_st_st", "mcneese_st")
    teams = replace(teams, "sam_houston", "sam_houston_st")
    teams = replace(teams, "sam_houston_st_st", "sam_houston_st")
    teams = replace(teams, "nicholls", "nicholls_st")
    teams = replace(teams, "nicholls_st_st", "nicholls_st")
    teams = replace(teams, "tarleton", "tarleton_st")
    teams = replace(teams, "tarleton_st_st", "tarleton_st")
    teams = replace(teams, "milwaukee", "wi_milwaukee")
    teams = replace(teams, "wi_wi_milwaukee", "wi_milwaukee")
    
    # Teams
    teams = replace(teams, "_mustangs", "")
    teams = replace(teams, "_spiders", "")
    teams = replace(teams, "_hawks", "_pa")
    teams = replace(teams, "_utes", "")
    teams = replace(teams, "_billikens", "")
    teams = replace(teams, "_mocs", "")
    teams = replace(teams, "_rams", "")
    teams = replace(teams, "_knights", "")
    teams = replace(teams, "_wildcats", "")
    teams = replace(teams, "_black_bears", "")
    teams = replace(teams, "_dolphins", "")
    teams = replace(teams, "_toreros", "")
    teams = replace(teams, "_coyotes", "")
    teams = replace(teams, "_retrievers", "")
    teams = replace(teams, "_warriors", "")
    return teams

def rename_odds(odds):
    id_to_team, team_to_id = get_map()
    o_teams = list(odds["team1"]) # + list(["team2"])
    o_teams = ["_".join(team.split(" ")).lower() for team in o_teams]
    o_teams = odds_rules(o_teams)
    o_teams = [team_to_id[team] for team in o_teams]
    odds["team1"] = o_teams
    o_teams = list(odds["team2"]) # + list(["team2"])
    o_teams = ["_".join(team.split(" ")).lower() for team in o_teams]
    o_teams = odds_rules(o_teams)
    o_teams = [team_to_id[team] for team in o_teams]
    odds["team2"] = o_teams
    # # not_found = list(set([team[:-7] for team in o_teams if team not in team_to_id.keys()]))
    # not_found = list([team for team in o_teams if team not in team_to_id.keys()])
    # print(not_found, "\n", len(not_found))
    return odds
def teams_rules(teams):
    teams = replace(teams, "-", "_")
    teams = replace(teams, ".", "")
    teams = replace(teams, "'", "")
    teams = replace(teams, "(", "")
    teams = replace(teams, ")", "")
    
    teams = replace(teams, "_state", "_st")
    teams = replace(teams, "saint", "st")
    teams = replace(teams, "university", "univ")
    teams = replace(teams, "_christian", "_chr")
    teams = replace(teams, "cal_st_", "cs_")
    
    teams = replace(teams, "loyola_maryland", "loyola_md")
    teams = replace(teams, "loyola_marymount", "loy_marymount")
    teams = replace(teams, "sacramento_st", "cs_sacramento")
    teams = replace(teams, "nc_st", "nc_state")
    teams = replace(teams, "st_johns_ny", "st_johns")
    teams = replace(teams, "uconn", "connecticut")
    teams = replace(teams, "ole_miss", "mississippi")
    teams = replace(teams, "kent_st", "kent")
    teams = replace(teams, "miami_ohio", "miami_oh")
    teams = replace(teams, "tennessee_martin", "tn_martin")
    teams = replace(teams, "northern_illinois", "n_illinois")
    teams = replace(teams, "george_washington", "g_washington")
    teams = replace(teams, "eastern_michigan", "e_michigan")
    teams = replace(teams, "east_washington", "e_washington")
    teams = replace(teams, "florida_atlantic", "fl_atlantic")
    teams = replace(teams, "georgia_southern", "ga_southern")
    teams = replace(teams, "florida_international", "florida_intl")
    teams = replace(teams, "eastern_illinois", "e_illinois")
    teams = replace(teams, "illinois_chicago", "il_chicago")
    # teams = replace(teams, "uic", "il_chicago")
    teams = replace(teams, "wisc_green_bay", "wi_green_bay")
    teams = replace(teams, "eastern_kentucky", "e_kentucky")
    teams = replace(teams, "central_michigan", "c_michigan")
    teams = replace(teams, "western_carolina", "w_carolina")
    teams = replace(teams, "college_of_charleston", "col_charleston")
    teams = replace(teams, "louisiana_monroe", "ulm")
    teams = replace(teams, "ul_monroe", "ulm")
    teams = replace(teams, "southeast_missouri_st", "se_missouri_st")
    teams = replace(teams, "umkc", "missouri_kc")
    teams = replace(teams, "little_rock", "ark_little_rock")
    teams = replace(teams, "ualr", "ark_little_rock")
    teams = replace(teams, "north_dakota_st", "n_dakota_st")
    teams = replace(teams, "south_dakota_st", "s_dakota_st")
    teams = replace(teams, "arkansas_pine_bluff", "ark_pine_bluff")
    teams = replace(teams, "southern_illinois", "s_illinois")
    teams = replace(teams, "northern_colorado", "n_colorado")
    teams = replace(teams, "middle_tenn_st", "mtsu")
    teams = replace(teams, "western_kentucky", "wku")
    teams = replace(teams, "louisiana_lafayette", "lafayette")
    teams = replace(teams, "coastal_carolina", "coastal_car")
    teams = replace(teams, "brigham_young", "byu")
    teams = replace(teams, "wisc_milwaukee", "wi_milwaukee")
    teams = replace(teams, "western_michigan", "w_michigan")
    teams = replace(teams, "miss_valley_st", "ms_valley_st")
    teams = replace(teams, "north_carolina_a&t", "nc_a&t")
    teams = replace(teams, "n_carolina_a&t", "nc_a&t")
    teams = replace(teams, "liu_sharks", "liu_brooklyn")
    teams = replace(teams, "umass", "massachusetts")
    teams = replace(teams, "stephen_", "s")
    teams = replace(teams, "prairie_view_a&m", "prairie_view")
    teams = replace(teams, "albany_great_danes", "suny_albany")
    teams = replace(teams, "st_francis_brooklyn", "st_francis_ny")
    teams = replace(teams, "texas_southern", "tx_southern")
    teams = replace(teams, "utsa_roadrunners", "ut_san_antonio")
    teams = replace(teams, "n_carolina_central", "nc_central")
    teams = replace(teams, "iu_indy", "iupui")
    teams = replace(teams, "iu_indianapolis", "iupui")
    teams = replace(teams, "western_illinois", "w_illinois")
    teams = replace(teams, "east_tennessee_st", "etsu")
    teams = replace(teams, "charleston_southern", "charleston_so")
    teams = replace(teams, "northwestern_st", "northwestern_la")
    teams = replace(teams, "st_marys", "st_marys_ca")
    teams = replace(teams, "st_marys_ca_ca", "st_marys_ca")
    teams = replace(teams, "mount_st_marys_ca", "mt_st_marys")
    teams = replace(teams, "csu_bakersfield", "cs_bakersfield")
    teams = replace(teams, "utah_valley_st", "utah_valley")
    teams = replace(teams, "ipfw", "pfw")
    teams = replace(teams, "purdue_fort_wayne", "pfw")
    teams = replace(teams, "northern_kentucky", "n_kentucky")
    teams = replace(teams, "usc_upstate", "sc_upstate")
    teams = replace(teams, "monmouth", "monmouth_nj")
    teams = replace(teams, "nebraska_o", "ne_omaha")
    teams = replace(teams, "siu_edwardsville", "siue")
    teams = replace(teams, "maryland_eastern_shore", "md_e_shore")
    teams = replace(teams, "md_east_shore", "md_e_shore")
    teams = replace(teams, "fdu", "f_dickinson")
    teams = replace(teams, "south_carolina_st", "s_carolina_st")
    teams = replace(teams, "florida_gulf_coast", "fgcu")
    teams = replace(teams, "california_baptist", "cal_baptist")
    teams = replace(teams, "grambling_st", "grambling")
    teams = replace(teams, "eastern_washington", "e_washington")
    teams = replace(teams, "texas_rio_grande_valley", "utrgv")
    teams = replace(teams, "north_carolina_central", "nc_central")
    teams = replace(teams, "massachusetts_lowell", "ma_lowell")
    teams = replace(teams, "central_arkansas", "cent_arkansas")
    teams = replace(teams, "texas_a&m_corpus_christi", "tam_c_christi")
    teams = replace(teams, "texas_a&m_cc", "tam_c_christi")
    teams = replace(teams, "miami_w", "miami_fl_w")
    teams = replace(teams, "miami_m", "miami_fl_m")
    teams = replace(teams, "st_thomas_minnesota", "st_thomas_mn")
    teams = replace(teams, "st_thomas_minn", "st_thomas_mn")
    teams = replace(teams, "san_josé_st", "san_jose_st")
    teams = replace(teams, "ualbany", "suny_albany")
    teams = replace(teams, "app_st", "appalachian_st")
    teams = replace(teams, "south_carolina_upstate", "sc_upstate")
    teams = replace(teams, "long_island_univ", "liu_brooklyn")
    teams = replace(teams, "central_connecticut_st", "central_conn")
    teams = replace(teams, "central_connecticut", "central_conn")
    teams = replace(teams, "detroit_mercy", "detroit")
    teams = replace(teams, "seattle_u", "seattle")
    teams = replace(teams, "utsa", "ut_san_antonio")
    teams = replace(teams, "winston_salem", "w_salem_st")
    teams = replace(teams, "mississippi_valley_st", "ms_valley_st")
    teams = replace(teams, "kennesaw_st", "kennesaw")
    teams = replace(teams, "pennsylvania", "penn")
    teams = replace(teams, "centenary_louisiana", "centenary")
    teams = replace(teams, "centenary_la", "centenary")
    teams = replace(teams, "middle_tennessee", "mtsu")
    teams = replace(teams, "kansas_city", "missouri_kc")
    teams = replace(teams, "queens_royals", "queens_nc")
    teams = replace(teams, "queens_univ", "queens_nc")
    teams = replace(teams, "southern_w", "southern_univ_w")
    teams = replace(teams, "southern_m", "southern_univ_m")
    teams = replace(teams, "southern_univ_mississippi", "southern_miss")
    teams = replace(teams, "tx_southern_univ", "tx_southern")
    teams = replace(teams, "ga_southern_univ", "ga_southern")
    teams = replace(teams, "st_josephs_w", "st_josephs_pa_w")
    teams = replace(teams, "st_josephs_m", "st_josephs_pa_m")
    teams = replace(teams, "tx_a&m_commerce", "east_texas_a&m")
    teams = replace(teams, "bryant_univ", "bryant")
    teams = replace(teams, "loyola_il", "loyola_chicago")
    teams = replace(teams, "maryland_baltimore_county", "umbc")
    teams = replace(teams, "southeastern_louisiana", "se_louisiana")
    teams = replace(teams, "st_thomas", "st_thomas_mn")
    teams = replace(teams, "the_citadel", "citadel")
    
    teams = replace(teams, "omaha", "ne_omaha")
    teams = replace(teams, "ne_ne_omaha", "ne_omaha")
    teams = replace(teams, "nc_greensboro", "unc_greensboro")
    teams = replace(teams, "uunc_greensboro", "unc_greensboro")
    teams = replace(teams, "nc_wilmington", "unc_wilmington")
    teams = replace(teams, "uunc_wilmington", "unc_wilmington")
    teams = replace(teams, "green_bay", "wi_green_bay")
    teams = replace(teams, "wi_wi_green_bay", "wi_green_bay")
    teams = replace(teams, "mcneese", "mcneese_st")
    teams = replace(teams, "mcneese_st_st", "mcneese_st")
    teams = replace(teams, "sam_houston", "sam_houston_st")
    teams = replace(teams, "sam_houston_st_st", "sam_houston_st")
    teams = replace(teams, "nicholls", "nicholls_st")
    teams = replace(teams, "nicholls_st_st", "nicholls_st")
    teams = replace(teams, "tarleton", "tarleton_st")
    teams = replace(teams, "tarleton_st_st", "tarleton_st")
    teams = replace(teams, "milwaukee", "wi_milwaukee")
    teams = replace(teams, "wi_wi_milwaukee", "wi_milwaukee")
    
    teams = replace(teams, "albany_ny", "suny_albany")
    teams = replace(teams, "american", "american_univ")
    teams = replace(teams, "bowling_green_st", "bowling_green")
    
    # teams = replace(teams, "_roadrunners", "")
    # teams = replace(teams, "_great_danes", "")
    # teams = replace(teams, "_sharks", "")
    return teams

def rename_teams(df):
    _, team_to_id = get_map()
    teams = df["SchoolY"]
    teams = teams_rules(teams)
    teams = [team_to_id[team] for team in teams]
    df["SchoolY"] = teams
    # not_found = list([team for team in teams if team not in team_to_id.keys()])
    # print(not_found[:10], "\n", len(not_found))
    # exit()
    return df